server:
  port: 8082    #default port where the service will be started
 
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:    
  application:
    name: ECM   #current service name to be used by the eureka server
  datasource.url: jdbc:oracle:thin:@localhost:1521:xe
  datasource.username: system
  datasource.password: orcl11g
  datasource.driver.class: oracle.jdbc.OracleDriver
  
  jpa.properties.hibernate.dialect: org.hibernate.dialect.OracleDialect
  jpa.hibernate.ddl-auto: update
  jpa.show.sql: true
  
     
management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
 
logging:
  level:
    com.example.howtodoinjava: DEBUG
    
